apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: password
    argocd.argoproj.io/instance: password-app
    k8s-app: gerador-test
    tier: test
    version: tester-1.0.0
  name: password-gerador-test
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: password
      k8s-app: gerador-test
      version: tester-1.0.0
  template:
    metadata:
      labels:
        app: password
        k8s-app: gerador-test
        version: tester-1.0.0
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: password-secret
          image: debian
          name: gerador-test
          args:
            - "bash"
            - "-c"
            - |
              while ! (apt-get update && apt-get install -y curl); do sleep 1s; done
              time_wait=2s
              x=1
              while sleep $time_wait
              do
                curl password-gerador-pass:8089/gerar/gmail/cicerow$x
                curl password-gerador-pass:8089/atualizar/gmail/cicerow$x/123123123
                curl password-gerador-pass:8089/listar
                curl password-gerador-pass:8089/naoexiste
                x=$(expr $x + 1)
                echo $x
              done

