apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: password
    k8s-app: listar-pass
    tier: facade
    version: master-1.218bde5
  name: password-listar-pass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password
      k8s-app: listar-pass
      version: master-1.218bde5
  template:
    metadata:
      labels:    
        app: password
        k8s-app: listar-pass
        version: master-1.218bde5
    spec:
      containers:
      - name: listar-pass
        image: 743322645550.dkr.ecr.us-east-1.amazonaws.com/password-listar-pass:master-1.218bde5
        ports:
        - containerPort: 8089 #Same in LISTAR_PASS_PORT config
        envFrom:
          - secretRef:
              name: password-secret
      imagePullSecrets:
        - name: ecr-credentials
