apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: password
    k8s-app: gerador-pass
    version: master-1.e50f19e
    tier: facade
  name: password-gerador-pass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password
      k8s-app: gerador-pass
      version: master-1.e50f19e
  template:
    metadata:
      labels:    
        app: password
        k8s-app: gerador-pass
        version: master-1.e50f19e
    spec:
      containers:
      - name: gerador-pass
        image: 743322645550.dkr.ecr.us-east-1.amazonaws.com/password-gerador-pass:master-1.e50f19e
        ports:
        - containerPort: 8089 #Same in GERADOR_PASS_PORT config
        envFrom:
          - secretRef:
              name: password-secret
      imagePullSecrets:
        - name: regcred
