apiVersion: v1
kind: Service
metadata:
  labels:
    app: password
    k8s-app: listar-pass
    tier: facade
  name: password-listar-pass
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: password
    k8s-app: listar-pass
  sessionAffinity: None
  type: ClusterIP
