apiVersion: v1
kind: Secret
metadata:
  name: password-secret
stringData:
  CONTAINER_ATUALIZAR: password-atualizar-pass
  CONTAINER_LISTAR: password-listar-pass
  PONTUACAO:  '@#$%()[]<>'
  GERADOR_PASS_PORT: '8089'
  ATUALIZAR_PASS_PORT: '8089'
  LISTAR_PASS_PORT: '8089'
  DATABASE_HOST: password-mysql #MySQL service name
  MYSQL_USER: passwordappuser
  MYSQL_PASSWORD: Iu7MPxYB9FM63EUkb1GkGpSWIbZDVwcwA
  MYSQL_ROOT_PASSWORD: mZ5Nh3X0v0SuuBtHD4ZPOAuTXVM6K4hV9
  MYSQL_DATABASE: passworddados
