apiVersion: v1
kind: Service
metadata:
  labels:
    app: password
    k8s-app: password-mysql
  name: password-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: password
    k8s: password-mysql

