apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: password
    k8s-app: atualizar-pass
    version: master-1.ca84535
    tier: facade
  name: password-atualizar-pass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password
      k8s-app: atualizar-pass
      version: master-1.ca84535
  template:
    metadata:
      labels:    
        app: password
        k8s-app: atualizar-pass
        version: master-1.ca84535
    spec:
      containers:
      - name: atualizar-pass
        image: 743322645550.dkr.ecr.us-east-1.amazonaws.com/password-atualizar-pass:master-1.ca84535
        ports:
        - containerPort: 8089 #Same in ATUALIZAR_PASS_PORT config
        envFrom:
          - secretRef:
              name: password-secret
      imagePullSecrets:
        - name: ecr-credentials
